### ISSUE TITLE
2D draw error

### ISSUE THREAD

**Issue by MajidSKhoshghalb** [mattmilten/TreeD#7]
Hey,

Nice package BTW. 3D version works just fine. I am running into an error when trying 2D:

`from treed import TreeD

treed = TreeD(
    probpath="blend2.mps",
    nodelimit=2000,
    showcuts=True
)
treed.solve()
fig = treed.draw2d()
fig.show(renderer='notebook')`

The error says:

`TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_25592\2275965518.py in <module>
----> 1 fig = treed.draw2d()
      2 fig.show(renderer='notebook')

~\AppData\Local\Programs\Python\Python37\lib\site-packages\treed\treed.py in draw2d(self)
    697         Xed = []
    698         Yed = []
--> 699         for edge in self.nxgraph.edges:
    700             Xed += [self.pos2d[edge[0]][0], self.pos2d[edge[1]][0], None]
    701             # Yed += [self.pos2d[edge[0]][1], self.pos2d[edge[1]][1], None]

TypeError: 'method' object is not iterable`

Also, any possibility to print all integer solution(s)?

**Comment by mattmilten** [comment]
Thanks!

On my machine, the code runs fine - I suppose there has been an API change in networkx. I am using version 2.5 and maybe the edges have been a method instead of an attribute in an earlier version? Can you try upgrading networkx to see whether that fixes the issue?

About the integer solutions: I guess that would also work. But then you don't have the tree connection anymore, because there won't be a new integer feasible solution at every node.

Cheers,
Matthias

**Comment by MajidSKhoshghalb** [comment]
For some technical reasons I downgraded mine to 1.9. The updated version resolves it, thanks! Integer solutions are OK now.
